// 蕪解 ERP 問卷資料定義 — questionnaire.html + qa-overview.html 共用
// 改題目只改這裡，兩個頁面同步更新

window.QUESTIONNAIRE_DEPTS = {
  procurement: {
    emoji:'📦', name:'採購', sub:'賴哥 + 木子',
    color:'#fb923c',
    intro:'收集生產／成本／工廠常數，影響每個項目的時間表與預算。',
    officialFillers:['賴哥','木子'],
    questions:[
      {id:'1.1', type:'pill-multi', vam:false, required:true,
        text:'你最常做的產品類型有哪些？',
        help:'複選，所有你經手過的都選。',
        options:['PVC 公仔','絨毛','壓克力立牌','文具（筆/便利貼）','包裝盒','服裝（T恤/帽）','其他']},
      {id:'1.2', type:'multi-range', vam:false, required:true,
        text:'PVC 公仔開模天數',
        help:'依複雜度給區間範圍',
        unit:'天',
        rows:[
          {label:'單款開模（標準複雜度）', minDefault:35, maxDefault:50},
          {label:'多款一起開模（6+1 或 9+1）', minDefault:45, maxDefault:60},
        ]},

      {id:'1.3', type:'multi-range', vam:true, required:true,
        text:'PVC 公仔量產時長（依數量 × 款式組合）',
        help:'依「一款多少只」+「總共多少款」回填區間範圍。其他組合可到末頁補充。',
        unit:'天',
        rows:[
          {label:'單款 1 萬只', minDefault:30, maxDefault:40},
          {label:'單款 2 萬只', minDefault:40, maxDefault:50},
          {label:'單款 3 萬只', minDefault:50, maxDefault:60},
          {label:'6+1 款（每款 ~1 萬只）', minDefault:40, maxDefault:55},
          {label:'9+1 款（每款 ~1 萬只）', minDefault:45, maxDefault:60},
          {label:'12+1 款（每款 ~1 萬只）', minDefault:50, maxDefault:65},
        ]},

      {id:'1.4', type:'multi-num', vam:false, required:false,
        text:'其他產品類型：量產 + 打樣天數',
        help:'各品類的量產天數 ＋ 打樣天數。沒做過填 0。',
        noSum:true,
        rows:[
          {label:'絨毛 量產', default:45, suffix:'天'},
          {label:'絨毛 打樣', default:21, suffix:'天'},
          {label:'壓克力／文具 量產', default:21, suffix:'天'},
          {label:'壓克力／文具 打樣', default:10, suffix:'天'},
          {label:'包裝盒 量產', default:14, suffix:'天'},
          {label:'包裝盒 打樣', default:7, suffix:'天'},
        ]},

      {id:'1.4a', type:'textarea', vam:false, required:false,
        text:'還有其他常用的生產／加工流程要補充嗎？',
        help:'寫流程名稱 + 所需天數，例如「鐳射標印製 7 天」「特殊上色工藝 +14 天」',
        placeholder:'選填'},

      {id:'1.5', type:'payment-stages', vam:false, required:true,
        text:'模具費付款階段（可動態增減）',
        help:'總和必須 = 100%。預設兩階段，可加可減。',
        defaults:[
          {label:'開模時付', pct:30, isAfterShip:false},
          {label:'驗收時付', pct:70, isAfterShip:false},
        ]},

      {id:'1.6', type:'payment-stages', vam:false, required:true,
        text:'量產費付款階段（可動態增減）',
        help:'總和必須 = 100%。「出貨後付」階段請填「出貨後幾天」要付清。',
        defaults:[
          {label:'下單時付', pct:30, isAfterShip:false},
          {label:'驗收時付', pct:40, isAfterShip:false},
          {label:'出貨後付', pct:30, isAfterShip:true, afterDays:30},
        ]},

      {id:'1.7', type:'multi-range', vam:true, required:true,
        text:'每款模具費（用售價回推會比較好估）',
        help:'以「售價 69 元 RMB 盲盒」為例，依款式數量回答區間範圍即可，不用定死。',
        unit:'萬 RMB',
        rows:[
          {label:'6+1 款（69 元盲盒）', minDefault:3, maxDefault:6},
          {label:'9+1 款（69 元盲盒）', minDefault:5, maxDefault:9},
          {label:'12+1 款（69 元盲盒）', minDefault:6, maxDefault:12},
          {label:'5cm 以下小公仔（單款）', minDefault:1, maxDefault:3},
        ]},

      {id:'1.8', type:'multi-num', vam:false, required:false,
        text:'各類樣品費預設（一套）',
        help:'依樣品類型分別估算，沒做過的填 0。如有其他類型，到末頁「補充新題目」加。',
        noSum:true,
        rows:[
          {label:'PVC 素胚（未上色）', default:1500, suffix:'元'},
          {label:'PVC 上色樣品', default:3000, suffix:'元'},
          {label:'絨毛樣品', default:2000, suffix:'元'},
          {label:'文創周邊樣品', default:1000, suffix:'元'},
        ]},

      {id:'1.9', type:'number-slider', vam:false, required:false,
        text:'試模費預設',
        help:'試模費＝工廠開完模具後，試打第一批產品驗證模具是否合格的費用',
        unit:'元 RMB', min:0, max:50000, default:5000},

      {id:'1.10', type:'vendor-list', vam:false, required:false,
        text:'常用工廠（top 5，可新增）',
        help:'每家工廠寫名稱 + 擅長品類（可複選）。如不夠用，到末頁「補充新題目」加。',
        count:5,
        categories:['PVC 公仔','絨毛','壓克力／立牌','文具','包裝盒','服裝','其他']},

      {id:'1.11', type:'number-slider', vam:true, required:true,
        text:'PVC 公仔大貨平均不良／耗損率？',
        help:'這會直接吃掉毛利，請依實際估算',
        unit:'%', min:0, max:10, default:3, step:0.5},

      {id:'1.12', type:'number-slider', vam:false, required:false,
        text:'絨毛／文創周邊不良率？',
        unit:'%', min:0, max:10, default:2, step:0.5},

      {id:'1.13', type:'pill-multi', vam:false, required:false,
        text:'量產時長為什麼會落到區間最高值？',
        help:'承接題 1.3 — 通常是哪些狀況讓量產拉長（複選）',
        options:['原料短缺','工廠排程衝突','工人不夠','模具出問題','配件供應商出問題','旺季產能不足','政策／環保限產','客戶臨時改規格','其他']},

      {id:'1.14', type:'textarea', vam:true, required:false,
        text:'目前是否有與工廠約定年度採購達標返點（Rebate）？',
        help:'若有，請寫工廠名稱 + 達標門檻 + 預估返點比例。這是隱藏利潤，VAM 戰情室要看。沒有就跳過。',
        placeholder:'例：A 工廠年採購額 ¥500 萬以上返 3%'},

      {id:'1.15', type:'textarea', vam:false, required:false,
        text:'採購流程中還有什麼系統該知道的？',
        help:'選填，自由分享',
        placeholder:'例：某工廠最近搬廠加 5 天...'},
    ],
  },

  logistics: {
    emoji:'🚚', name:'物流／報關', sub:'高維 + Shawn',
    color:'#34d399',
    intro:'物流路線、報關方式、貨代清單 — 影響項目交期與毛利計算。',
    officialFillers:['高維','Shawn'],
    questions:[
      {id:'2.1', type:'route-list', vam:true, required:true,
        text:'物流路線清單（含天數 + 成本佔比）',
        help:'列出公司常用的路線。每條路線一行，可新增、修改、刪除。海運 / 空運 / 陸運 整合在這。',
        fromOptions:['北京','上海','廣州','深圳','其他'],
        toOptions:['台灣','曼谷','香港','東京（日本）','首爾（韓國）','美國','歐洲','國內城市','其他'],
        modeOptions:['海運（一般）','海運（加急）','空運（一般）','空運（加急）','陸運','快遞'],
        defaults:[
          {from:'北京', to:'台灣', mode:'海運（一般）', days:15, costPct:8},
          {from:'北京', to:'曼谷', mode:'海運（一般）', days:18, costPct:10},
          {from:'北京', to:'香港', mode:'海運（一般）', days:7, costPct:6},
          {from:'北京', to:'國內城市', mode:'陸運', days:5, costPct:3},
        ]},
      {id:'2.2', type:'pill-single', vam:true, required:true,
        text:'跨境出口報關時，貨值通常按什麼標準報？',
        help:'這是 Transfer Pricing 防線。系統做合併報表會看這個。',
        options:['按 Transfer Pricing（內部約定價）','按工廠實際進價','按市場零售價打折','視客戶要求調整','其他']},
      {id:'2.2a', type:'pill-single', vam:false, required:false,
        text:'報關時會低報或高報嗎？',
        help:'承接上題 — 通常為了節稅、配合客戶清關、或其他原因，會調整申報貨值嗎？',
        options:['幾乎不會（按實申報）','偶爾配合客戶調整','常常會調整','視情況而定']},
      {id:'2.3', type:'multi-num', vam:false, required:true,
        text:'實體樣品寄海外版權方（單趟天數）',
        help:'各地區單趟物流時間，沒寄過的填 0',
        noSum:true,
        rows:[
          {label:'日本', default:5, suffix:'天'},
          {label:'韓國', default:5, suffix:'天'},
          {label:'美國', default:7, suffix:'天'},
          {label:'歐洲', default:7, suffix:'天'},
          {label:'東南亞', default:5, suffix:'天'},
        ]},
      {id:'2.4', type:'number-slider', vam:false, required:false,
        text:'報關文件準備緩衝？',
        help:'從下單到能出關的緩衝天數',
        unit:'天', min:0, max:14, default:3},
      {id:'2.5', type:'number-slider', vam:false, required:false,
        text:'旺季（11-12 月）跨境物流 +幾天緩衝？',
        unit:'+天', min:0, max:21, default:5},
      {id:'2.6', type:'text-multi', vam:false, required:false,
        text:'國內物流商（top 3）',
        help:'國內運輸的物流公司',
        count:3},
      {id:'2.7', type:'vendor-list', vam:false, required:false,
        text:'國際貨代（top 5）',
        help:'跨境物流通常聯繫貨代（貨代會配合物流商＋報關行）。寫貨代名稱＋他們擅長的路線。',
        count:5,
        categories:['日本線','韓國線','東南亞線','歐美線','港澳台線','整櫃','散櫃']},
      {id:'2.8', type:'textarea', vam:false, required:false,
        text:'物流／報關還有什麼系統該提醒的？',
        placeholder:'例：某些 IP 商品需特殊報關 / 某些路線旺季要提前訂艙...'},
    ],
  },

  sales: {
    emoji:'💼', name:'業務', sub:'安然 + 董亮 + 德寶',
    color:'#a78bfa',
    intro:'客戶帳期 + 付款結構 + 退貨損耗 — 影響現金流預測與毛利計算。版權方送審節奏移到 IP 庫常數問卷。',
    officialFillers:['安然','董亮','德寶'],
    questions:[
      {id:'3.1', type:'number-slider', vam:false, required:true,
        text:'你目前固定接觸的客戶數？',
        unit:'家', min:1, max:200, default:30},

      {id:'3.2', type:'pill-single', vam:true, required:true,
        text:'KA 大客戶（如誠品／萬代等）通常的付款期限？',
        help:'下面選項用白話說，請挑最常見的',
        options:['出貨時就收款','出貨後 30 天收款','出貨後 60 天收款','出貨後 90 天收款']},

      {id:'3.3', type:'pill-single', vam:true, required:true,
        text:'流通商（中盤／經銷）通常的付款期限？',
        options:['出貨時就收款','出貨後 30 天收款','出貨後 60 天收款','出貨後 90 天收款']},

      {id:'3.4', type:'pill-single', vam:true, required:true,
        text:'電商通路通常的付款期限？',
        options:['出貨時就收款','出貨後 30 天收款','出貨後 60 天收款','出貨後 90 天收款']},

      {id:'3.5', type:'payment-stages', vam:true, required:true,
        text:'KA 大客戶付款結構（可動態增減）',
        help:'通常分幾次付？每次多少 %？「出貨後付」的階段請填出貨後幾天。總和需 = 100%。',
        defaults:[
          {label:'訂金（簽單時付）', pct:30, isAfterShip:false},
          {label:'尾款（出貨後付）', pct:70, isAfterShip:true, afterDays:60},
        ]},

      {id:'3.6', type:'payment-stages', vam:true, required:true,
        text:'流通商付款結構（可動態增減）',
        help:'通常分幾次付？',
        defaults:[
          {label:'貨款（出貨後付清）', pct:100, isAfterShip:true, afterDays:60},
        ]},

      {id:'3.7', type:'payment-stages', vam:true, required:false,
        text:'電商通路付款結構',
        help:'若不直接對電商可略過',
        defaults:[
          {label:'貨款（出貨後付清）', pct:100, isAfterShip:true, afterDays:30},
        ]},

      {id:'3.8', type:'multi-num', vam:true, required:true,
        text:'各客群平均退貨／損耗率',
        help:'依客群類型分別估算。「退貨損耗」會直接吃掉毛利。',
        noSum:true,
        rows:[
          {label:'KA 大客戶', default:2, suffix:'%'},
          {label:'流通商', default:3, suffix:'%'},
          {label:'電商通路', default:5, suffix:'%'},
        ]},

      {id:'3.8a', type:'multi-num', vam:true, required:false,
        text:'通路常態性扣抵費用佔該客戶營收 %（除退貨外）',
        help:'KA / 流通商常見的「上架費 / 行銷贊助 / 退換貨補貼」等隱形扣抵。這會直接吃毛利。沒有就填 0。',
        noSum:true,
        rows:[
          {label:'KA 大客戶 通路費佔比', default:0, suffix:'%'},
          {label:'流通商 通路費佔比', default:0, suffix:'%'},
          {label:'電商 平台抽成（如適用）', default:0, suffix:'%'},
        ]},

      {id:'3.9', type:'text-multi', vam:false, required:false,
        text:'會拖款的客戶（top 3）',
        help:'選填，協助系統提醒催款',
        count:3},

      {id:'3.10', type:'text-multi', vam:false, required:false,
        text:'準時付款的客戶（top 3）',
        help:'選填',
        count:3},

      {id:'3.11', type:'text-multi', vam:false, required:false,
        text:'你個人最常追的客戶（top 3）',
        help:'選填',
        count:3},

      {id:'3.12', type:'textarea', vam:false, required:false,
        text:'業務跟客戶互動還有什麼系統該知道的?',
        placeholder:'例：某客戶 Q4 旺季帳期會拖到 Net90...'},
    ],
  },

  shawn: {
    emoji:'🎯', name:'COO 整合', sub:'Shawn',
    color:'#22c55e',
    intro:'公司整體收入結構 + 毛利目標 + VAM 分配 — 預算模板的核心。',
    officialFillers:['Shawn'],
    questions:[
      {id:'4.1', type:'multi-num', vam:true, required:true,
        text:'預估 2026 年收入結構比例',
        help:'總和必須 = 100%',
        rows:[
          {label:'批發', default:50, suffix:'%'},
          {label:'快閃', default:30, suffix:'%'},
          {label:'電商', default:15, suffix:'%'},
          {label:'其他', default:5, suffix:'%'},
        ], sumTarget:100},
      {id:'4.2', type:'number-slider', vam:true, required:true,
        text:'批發業務目標毛利率?',
        unit:'%', min:0, max:50, default:30},
      {id:'4.3', type:'number-slider', vam:true, required:true,
        text:'快閃業務目標毛利率?',
        unit:'%', min:0, max:50, default:35},
      {id:'4.4', type:'number-slider', vam:true, required:true,
        text:'電商業務目標毛利率?',
        unit:'%', min:0, max:50, default:25},
      {id:'4.5', type:'number-slider', vam:false, required:false,
        text:'預算建立時 default 緩衝比例？',
        help:'預算超支接受幾%',
        unit:'%', min:0, max:30, default:10},
      {id:'4.6', type:'number-slider', vam:false, required:true,
        text:'一個 PVC 公仔項目從預算到出貨平均幾個月?',
        unit:'個月', min:3, max:12, default:6},
      {id:'4.7', type:'pill-multi', vam:false, required:false,
        text:'你會主動關心的項目進度節點?',
        options:['預算建立','提案通過','設計定稿','送審通過','打樣完成','量產完成','出貨','結案']},
      {id:'4.8', type:'textarea', vam:false, required:false,
        text:'預算建立流程／最常忘記填的欄位／其他盲點?',
        placeholder:'例：每次都忘記填物流費...'},
    ],
  },

  design: {
    emoji:'🎨', name:'設計／企劃', sub:'Bevis + 珮玲 + 詩彤',
    color:'#ec4899',
    intro:'產品設計流水線 — 每階段的天數、退回原因、外包設定全部綁定到該階段。',
    officialFillers:['Bevis','珮玲','詩彤'],
    questions:[
      {id:'5.1', type:'design-stage-list', vam:true, required:true,
        text:'產品設計流水線階段',
        help:'每個階段獨立設定：天數 / 退回常見原因 / 是否需外包 / 外包報價類型。預設 7 階段，可勾選「不需要」、改名、新增。',
        refusalOptions:['創意方向不對','顏色不符','造型不符','文字／文案','授權範圍','規格／尺寸','其他'],
        outsourceTypeOptions:['平面 2D 設計','2D 手繪／插畫','3D 建模','文案／企劃','其他'],
        defaults:[
          {name:'概念提案 / IP 選品', enabled:true, days:5,
           refusalReasons:['創意方向不對'], outsource:false,
           outsourceType:'', outsourceMin:0, outsourceMax:0},
          {name:'草圖 sketch', enabled:true, days:3,
           refusalReasons:['創意方向不對','造型不符'], outsource:false,
           outsourceType:'', outsourceMin:0, outsourceMax:0},
          {name:'平面 2D 設計', enabled:true, days:7,
           refusalReasons:['顏色不符','造型不符','文字／文案'], outsource:true,
           outsourceType:'平面 2D 設計', outsourceMin:5000, outsourceMax:12000},
          {name:'3D 建模', enabled:true, days:10,
           refusalReasons:['造型不符','規格／尺寸'], outsource:true,
           outsourceType:'3D 建模', outsourceMin:10000, outsourceMax:25000},
          {name:'打樣樣品（PVC 素胚 + 上色）', enabled:true, days:14,
           refusalReasons:['顏色不符','造型不符','規格／尺寸'], outsource:false,
           outsourceType:'', outsourceMin:0, outsourceMax:0},
          {name:'送審（版權方）', enabled:true, days:14,
           refusalReasons:['顏色不符','造型不符','授權範圍'], outsource:false,
           outsourceType:'', outsourceMin:0, outsourceMax:0},
          {name:'定稿 / 量產前審核', enabled:true, days:3,
           refusalReasons:[], outsource:false,
           outsourceType:'', outsourceMin:0, outsourceMax:0},
        ]},

      {id:'5.2', type:'textarea', vam:false, required:false,
        text:'設計流程盲點／流水線之外還有什麼？',
        help:'選填。例如：等版權方回覆最久、某類產品額外需求、跨部門協作的卡點...',
        placeholder:'選填'},
    ],
  },

};
